esphome:
  name: ir-blaster
  friendly_name: IR Blaster

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "YOUR_ENCRYPTION_KEY"

ota:
  password: "fa8aa9e85fdd76f3ae72ad109eceed93"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ir-Blaster Fallback Hotspot"
    password: "Password"

web_server:
  port: 80
  
# remote command reciever
remote_receiver:
  pin:
    number: 14
    inverted: true
  dump: all
# Remote Command Transmitter
remote_transmitter:
  pin: 4
  # Infrared remotes use a 50% carrier signal
  carrier_duty_percent: 50%

button:
  - platform: template
    name: TV Power Toggle
    id: PwrTog
    on_press:
      - remote_transmitter.transmit_sony:
          repeat:
            times: 3
            wait_time: 10ms
          data: 0x00000A90
          nbits: 12

  - platform: template
    name: TV Volume Up
    id: VolUp
    on_press:
      - remote_transmitter.transmit_sony:
          repeat:
            times: 3
            wait_time: 10ms
          data: 0x00000490
          nbits: 12

  - platform: template
    name: TV Volume Down
    id: VolDown
    on_press:
      - remote_transmitter.transmit_sony:
          repeat:
            times: 3
            wait_time: 10ms
          data: 0x00000C90
          nbits: 12

captive_portal:
    
